---
- name: add repo
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian trusty contrib
    update_cache: yes
    state: present
- name: add key
  apt_key:
    url: {{ item }}
    state: present
    with_items:
      - https://www.virtualbox.org/download/oracle_vbox_2016.asc -O-
      - https://www.virtualbox.org/download/oracle_vbox.asc -O-
- name: install awscli boto3 virtualbox
  pip:
    name: {{ item }}
    with_items:
      - awscli
      - boto3
      - virtualbox-5.2
